# Generated by Django 6.0.6 on 2026-06-15 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('assigned_date', models.DateField()),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Assigned', max_length=20)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.intern')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('total_task', models.IntegerField(default=1)),
                ('completed_task', models.IntegerField(default=0)),
                ('assigned_date', models.DateField()),
                ('submission_date', models.DateField()),
                ('status', models.CharField(choices=[('Incomplete', 'Incomplete'), ('Complete', 'Complete')], default='Incomplete', max_length=20)),
                ('intern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.intern')),
                ('trainee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.trainee')),
            ],
        ),
    ]
