# Generated by Django 5.2.4 on 2026-06-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_leave_project_task'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
