# Generated by Django 5.2.4 on 2026-06-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='first_installment_paid',
            field=models.BooleanField(default=False),
        ),
    ]
