# Generated by Django 6.0.6 on 2026-06-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_trainee_address_trainee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_file',
            field=models.FileField(blank=True, null=True, upload_to='batch_files/'),
        ),
    ]
