# Generated by Django 6.0.6 on 2026-06-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_batch_batch_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Business Team Approved', 'Business Team Approved')], default='Pending', max_length=30),
        ),
    ]
