# Generated by Django 6.0.6 on 2026-06-17 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_systemsetting_admin_batch_course_control_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed_task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='intern',
        ),
        migrations.RemoveField(
            model_name='task',
            name='submission_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='trainee',
        ),
        migrations.AddField(
            model_name='task',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.batch'),
        ),
        migrations.AddField(
            model_name='task',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.trainer'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(default='Task', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='total_task',
            field=models.IntegerField(default=30),
        ),
        migrations.CreateModel(
            name='TraineeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_task', models.IntegerField(default=0)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Incomplete', 'Incomplete'), ('Complete', 'Complete'), ('Dropout', 'Dropout')], default='Incomplete', max_length=20)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trainee')),
            ],
            options={
                'unique_together': {('trainee', 'task')},
            },
        ),
    ]
