# Generated by Django 6.0.6 on 2026-06-17 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_task_completed_task_remove_task_intern_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='traineetask',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='project',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.batch'),
        ),
        migrations.AddField(
            model_name='project',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.trainer'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to_all',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='traineetask',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='intern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.intern'),
        ),
        migrations.AlterField(
            model_name='task',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.batch'),
        ),
        migrations.AlterField(
            model_name='task',
            name='day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='traineetask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainee_tasks', to='core.task'),
        ),
    ]
