# Generated by Django 6.0.6 on 2026-06-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_enquiry_address_enquiry_age_enquiry_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eligibility',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
