# Generated by Django 6.0.6 on 2026-06-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_candidate_age_eligibility_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibility',
            name='is_auto_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
