# Generated by Django 6.0.6 on 2026-06-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_eligibility_is_auto_eligible'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, help_text='e.g., UPI, Bank Transfer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.CharField(blank=True, help_text='e.g., 2 - Installment, One - Time Payment', max_length=100, null=True),
        ),
    ]
