# Generated by Django 6.0.6 on 2026-06-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_payment_due_date_payment_payment_method_payment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
