# Generated by Django 6.0.6 on 2026-06-19 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_contactquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='notification_type',
            field=models.CharField(choices=[('REPORT', 'Report'), ('PAYMENT', 'Payment'), ('ENQUIRY', 'Enquiry'), ('GENERAL', 'General'), ('TASK', 'Task'), ('BATCH', 'Batch')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
