# Generated by Django 6.0.6 on 2026-06-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_businessteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intern',
            name='overall_status',
            field=models.CharField(default='Good Performance', max_length=50),
        ),
        migrations.AddField(
            model_name='intern',
            name='trainer_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
